#!/bin/bash
isExistApp = `pgrep nginx`
if [[ -n  $isExistApp ]]; then
    service nginx stop        
fi

isExistApp = `pgrep httpd`
if [[ -n  $isExistApp ]]; then
    service httpd stop        
fi

isExistApp = `pgrep apache2`
if [[ -n  $isExistApp ]]; then
    service apache2 stop        
fi